version: '3'
services:
  web:
    build:
      context: ./
      # target: dev
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "8001:8001"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    depends_on:
      - mongodb
    links:
      - mongodb
  mongodb:
    image: mongo:3.5
    ports:
      - "27017:27017"
    command: mongod --port 27018 --bind_ip_all
